// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ISingleRowService.cs" company="EPAM Systems">
//   Copyright 2015
// </copyright>
// <summary>
//   Autogenerated Web Services
// </summary>
// --------------------------------------------------------------------------------------------------------------------
namespace HyperWebApp1.Services
{
	using Entities;
	using HyperWebApp1.Service.Pattern;

    /// <summary>
    /// The singlerow service interface
    /// </summary>
    public interface ISingleRowService : IService<SingleRow>
    { }
}
