// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ISingleRowRepository.cs" company="EPAM Systems">
//   Copyright 2015
// </copyright>
// <summary>
//   Autogenerated Web Services
// </summary>
// --------------------------------------------------------------------------------------------------------------------
namespace HyperWebApp1.Repository
{
	using Entities;
	using global::HyperWebApp1.Repository.Pattern.Repositories;

    /// <summary>
    /// The singlerow Repository interface
    /// </summary>   
	public interface ISingleRowRepository : IRepository<SingleRow>
    { } 
}
