// --------------------------------------------------------------------------------------------------------------------
// <copyright file="SingleRowRepository.cs" company="EPAM Systems">
//   Copyright 2015
// </copyright>
// <summary>
//   Autogenerated Web Services
// </summary>
// --------------------------------------------------------------------------------------------------------------------
namespace HyperWebApp1.Repository
{
	using Entities;
	using global::HyperWebApp1.Repository.Mongo;	
	
	/// <summary>
    /// The singlerow Repository.
    /// </summary>
    public class SingleRowRepository : Repository<SingleRow>, ISingleRowRepository
    {    
        /// <summary>
        /// Initializes a new instance of the <see cref="SingleRowRepository"/> class.
        /// </summary>
        /// <param name="unitOfWork">The unit of work.</param>
        /// <remarks>
        /// Default constructor defaults to "DefaultConnection" key for connectionstring.
        /// </remarks>
        public SingleRowRepository() : base()
		 { }
	}
}
